#!/bin/sh

### BEGIN INIT INFO
# Provides:          kocom
# Required-Start:    $remote_fs $all
# Required-Stop:     $remote_fs $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: kocom init script
# Description:       initscript by djjproject
### END INIT INFO


DESC="kocom rs485"
NAME=kocom
PIDFILE=/var/run/$NAME.pid
COMMAND="/usr/bin/node"
DAEMON_ARGS="/home/hassio/kocom/kocom_rs485.js"
RUN_AS=root

d_start() {
    start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --chuid $RUN_AS --exec $COMMAND -- $DAEMON_ARGS
}

d_stop() {
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    if [ -e $PIDFILE ]
        then rm $PIDFILE
    fi
}

case $1 in
    start)
    echo -n "Starting $DESC: $NAME"
    d_start
    echo "."
    ;;
    stop)
    echo -n "Stopping $DESC: $NAME"
    d_stop
    echo "."
    ;;
    restart)
    echo -n "Restarting $DESC: $NAME"
    d_stop
    sleep 1
    d_start
    echo "."
    ;;
    *)
    echo "usage: $NAME {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
